core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import logout
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('grading.urls')),
    path('', include('district.urls')),
    path('', include('customsettings.urls')),
    path('', include('customadmin.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customsettings/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('update_schoolprofile/<int:pk>/', views.update_schoolprofile, name='update_schoolprofile'),
    path('school_profile_create_step1/', views.school_profile_create_step1, name='school_profile_create_step1'),
    path('schoolprofile_details/<int:id>/', views.schoolprofile_details, name='schoolprofile_details'),
   
    path('class_name/', views.class_name, name='class_name'),
    path('setup_step7/', views.setup_step7, name='setup_step7'),
    path('create_schoolsubjects_step2/',views.create_schoolsubjects_step2,name='create_schoolsubjects_step2'),
    path('subject_list/',views.subject_list,name='subject_list'),
    path('edit_schoolsubjects/<int:pk>/', views.edit_schoolsubjects, name='edit_schoolsubjects'),
    path('all_classes/', views.all_classes,name='all_classes'),
    path('teacher_list/',views.teacher_list, name='teacher_list'),
   
]

customadmin/models.py
import datetime
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.http import HttpResponseForbidden


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name,  password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name,  **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name,  password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, first_name, last_name,  password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    USER_TYPE = (
        ('student', 'STUDENT'),
        ('teacher', 'TEACHER'),
        ('school_admin', 'SCHOOL_ADMIN'),
        ('deputy_head', 'DEPUTY_HEAD'),
        ('school_head', 'SCHOOL_HEAD'),
        ('district_admin', 'DISTRICT_ADMIN'),
    )

    POSITION = (
        ('admin', 'ADMIN'),
        ('user', 'USER'),
        ('staff', 'STAFF'),
        ('student', 'STUDENT'),
    )

    email       = models.EmailField(unique=True)
    first_name  = models.CharField(max_length=30)
    last_name   = models.CharField(max_length=30)
    position    = models.CharField(max_length=30, choices=POSITION)
    user_type   = models.CharField(max_length=30, choices=USER_TYPE)
    is_active   = models.BooleanField(default=True)
    is_staff    = models.BooleanField(default=False)
    is_school_superuser = models.BooleanField(default=False)
    objects     = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def save(self, *args, **kwargs):
        if not self.pk:
            self.set_password('munyaradzi')
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

customsettings/models.py
from django.db import models
from district.models import District_School_Registration,GradeLevel,AcademicCalendar,Subjects,SchoolAdminProfile
from django.utils.translation import gettext_lazy as _


class SchoolProfile(models.Model): 
    school_admin =models.ForeignKey(District_School_Registration, on_delete=models.CASCADE, blank=True, null=True,related_name='schooladmin')   
    school       = models.OneToOneField(District_School_Registration, on_delete=models.CASCADE, blank=True, null=True)
    school_logo  = models.ImageField(upload_to='school_logos/', blank=True, null=True)
    school_subjects   = models.ManyToManyField('SchoolSubject')
    is_setup_complete = models.BooleanField(default=False)

    def __str__(self):
       return f'{self.school}'

    
    
class ClassName(models.Model):
    CLASS_CHOICES = [
        ('A', 'A'),('B', 'B'),('C', 'C'),('D', 'D'),('E', 'E'),
    ]
    schoolprofile  = models.ForeignKey(SchoolProfile, on_delete=models.CASCADE,blank=True, null=True)   
    grd_level      = models.ForeignKey(GradeLevel, on_delete=models.CASCADE, null=True, blank=True)
    classname      = models.CharField(max_length= 1, choices=CLASS_CHOICES)
    academic_year  = models.ForeignKey(AcademicCalendar, on_delete=models.CASCADE, null=True, blank=True)
    date           = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.grd_level} {self.classname}-({self.academic_year}){self.schoolprofile }"    
    

class SchoolSubject(models.Model):
    subjects   = models.ManyToManyField(Subjects)
    school     = models.ForeignKey(SchoolProfile, on_delete=models.CASCADE,blank=True, null=True) 

    def __str__(self):
        return ', '.join(str(subject) for subject in self.subjects.all())
    
 
  

district/models.py
import datetime
from django.db import models
from customadmin.models import CustomUser


class District(models.Model):
    district = models.CharField(max_length=255,blank=True, null=True)
    
    def __str__(self):
        return f'{self.district}' 


class District_School_Registration(models.Model):
   
    district      = models.ForeignKey(District,on_delete=models.CASCADE,blank=True, null=True)
    school        = models.CharField(max_length=255,blank=True, null=True)
    address       = models.TextField(blank=True, null=True)
    phone_number  = models.CharField(max_length=20,blank=True, null=True)
    email         = models.EmailField(blank=True, null=True)
   
    def __str__(self):
        return f'{self.school}' 


class SchoolAdminProfile(models.Model):
    school_admin      = models.OneToOneField(CustomUser, on_delete=models.CASCADE,blank=True, null=True)
    contact_number    = models.CharField(max_length=255,blank=True, null=True)
    email             = models.EmailField(blank=True, null=True)
    school            = models.ForeignKey(District_School_Registration, on_delete=models.CASCADE,blank=True, null=True)
    admin             = models.CharField(max_length=10,choices=[('admin1','admin1'),('admin2','admin2'),('admin3','admin3')],null=True,blank=True)
    
    def __str__(self):
        return f'{self.school_admin}' 


class DistrictAdminProfile(models.Model):
    district_admin   = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='district_admin_profile')
    district_name    = models.CharField(max_length=255,blank=True, null=True)
    contact_number   = models.CharField(max_length=255,blank=True, null=True)
    email            = models.EmailField(blank=True, null=True)
    district_schools = models.ManyToManyField(District_School_Registration)
    admin   = models.CharField(max_length=10,choices=[('admin1','admin1'),('admin2','admin2'),('admin3','admin3')],null=True,blank=True)
    

    def __str__(self):
        return f'{self.district_admin}' 
    
    
    
class SchoolHeadProfile(models.Model):
    school_head      = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='SchoolHead_profile')
    phone_number     =  models.CharField(max_length=255,blank=True, null=True)
    email            = models.EmailField(blank=True, null=True)
    school           = models.ForeignKey(District_School_Registration, on_delete=models.CASCADE,blank=True, null=True)
    
    def __str__(self):
        return f'{self.school_head}' 
        
        
class Subjects(models.Model):
    subjects = models.CharField(max_length=50,blank=True,null=True)   

    def __str__(self):
        return f'{self.subjects}'  

    class Meta:
        verbose_name_plural = 'Subjects' 
        
        
class Holiday(models.Model):

    date = models.DateField()
    name = models.CharField(max_length=200)
    note = models.TextField()
   
    def __str__(self):
        return self.name         
        
        
class AcademicCalendar(models.Model):
    
    academic_year = models.PositiveIntegerField(default=datetime.datetime.now().year, blank=True, null=True)

    # Fields for each term
    term_1_start_date = models.DateField(blank=True, null=True)
    term_1_end_date   = models.DateField(blank=True, null=True)
    term_2_start_date = models.DateField(blank=True, null=True)
    term_2_end_date   = models.DateField(blank=True, null=True)
    term_3_start_date = models.DateField(blank=True, null=True)
    term_3_end_date   = models.DateField(blank=True, null=True)
    term_4_start_date = models.DateField(blank=True, null=True)
    term_4_end_date   = models.DateField(blank=True, null=True)
    holidays          = models.ManyToManyField(Holiday, related_name="academic_calendars")
    is_current        = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.academic_year}'    
    
    
       
    
    
class GradeLevel(models.Model):
    class GradeLevels(models.IntegerChoices):
        EIGHT  = 8, '8'
        NINE   = 9, '9'
        TEN    = 10, '10'
        ELEVEN = 11, '11'
        TWELVE = 12, '12'
        
    grade_level = models.IntegerField(choices=GradeLevels.choices)
   
    
    def __str__(self):
        return str(self.grade_level)    

customsettings/forms.py
from django import forms
from .models import *

class SchoolProfileForm(forms.ModelForm):
   

    class Meta:
        model = SchoolProfile
        fields = ['school_logo']

    def save(self, commit=True):
        instance = super(SchoolProfileForm, self).save(commit=False)
        if commit:
            instance.save()
            self.save_m2m()  # Save the many-to-many relationships
        return instance
    

class SchoolSubjectForm(forms.ModelForm):
    school_subjects = forms.ModelMultipleChoiceField(queryset=Subjects.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = SchoolSubject
        fields = ['school_subjects']


class ClassNameForm(forms.ModelForm):
    class Meta:
        model = ClassName
        fields = ['grd_level','classname']


class GradeLevelForm(forms.ModelForm):
    class Meta:
        model = GradeLevel
        fields = ['grade_level']  

templates/customsettings/academic_year.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
 <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"class="btn btn-info">Submit</button>
 </form>
{% endblock %}

templates/customsettings/all_classes.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<style>
 
    
    .tab {
        overflow: hidden;
       
        margin-bottom: 20px;
        display: flex;
        justify-content: center;
    }
    
    .tab button {
        background-color: #446E9B;  
        border: none;
       
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 18px;
    }
    
    .tab button.active {
        background-color: #071555f1;
        color: white;
    }
    
    .tabcontent {
        display: none;
    }
    
    .class-details {
       
        margin-bottom: 20px;
        margin-left: 20px; /* Add left margin */
    }
    .scroll-container {
        max-height: 80vh; /* Control the height */
        overflow-y: auto; /* Ensure vertical scrolling */
    }
</style>
<div class="col-lg-8 offset-md-1 scroll-container">
    <div class="division mt-5">
        <h2 class="text-center ">All Classes</h2>
        <hr class="text-success">

        <div class="tab rounded">
            {% for grade_level, class_data in grade_level_data.items %}
            <button class="tablinks {% if forloop.first %}active{% endif %}" onclick="openTab(event, 'grade{{ grade_level }}')">Grade {{ grade_level }}</button>
            {% endfor %}
        </div>

        {% for grade_level, class_data in grade_level_data.items %}
        <div id="grade{{ grade_level }}" class="tabcontent {% if forloop.first %}active{% endif %}">
            {% for data in class_data %}
            <div class="class-details  border m-2 p-2 rounded">
                <h6 class=" text-center"><strong>{{ data.classroom.name }}</strong></h6>
                <div class="d-flex">
                    <strong>Class Teacher:&nbsp;&nbsp;</strong>
                    {{ data.classroom.class_teacher.first_name|default:"No teacher assigned" }} {{ data.classroom.class_teacher.last_name|default:"" }}
                </div>
                <div class="d-flex">
                    <strong>Total Students:&nbsp;&nbsp;</strong>
                    {{ data.total_students }}
                </div>

                <div class="d-flex">
                    <strong>Gender Count:</strong>
                </div>
                <div class="d-flex">
                    <div class="col-md-4">
                        Girls: {{ data.female_count }}
                        <div class="progress">
                            <div class="progress-bar bg-success" role="progressbar" style="width: {{ data.female_percentage }}%;" aria-valuenow="{{ data.female_count }}" aria-valuemin="0" aria-valuemax="{{ data.total_students }}"></div>
                        </div>
                       
                    </div>&nbsp;&nbsp;
                    <div class="col-md-4">
                        Boys: {{ data.male_count }}
                        <div class="progress">
                            <div class="progress-bar bg-primary" role="progressbar" style="width: {{ data.male_percentage }}%;" aria-valuenow="{{ data.male_count }}" aria-valuemin="0" aria-valuemax="{{ data.total_students }}"></div>
                        </div>
                       
                    </div>
                </div>
                <hr >
                <a href="{% url 'classroom_details' pk=data.classroom_pk %}" class="btn btn-dark">Class Details</a>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

    <script>
        function openTab(evt, tabName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].classList.remove("active");
            }
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.classList.add("active");
        }
        // Activate the default tab
        document.querySelector('.tablinks.active').click();
    </script>

{% endblock %}

templates/customsettings/class_name.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="section1 mt-5 offset-1 d-flex gap-2">
  <div class="col-md-6 border p-5 shado">
  <h2 >  Class Name</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-flex">
          <button type="submit" class="btn btn-dark">Save and make another Grade</button>&nbsp;&nbsp;
          <br>
          <a href="{% url 'setup_step7' %}"class="btn btn-dark ">done</a>

        </div>
        
    </form>
  </div>
    <div class="col-3 bg1 p-4">
      
       {% for class in allclasses%}
      <li>{{class}}</li>
      {% endfor%}
    </div>
    
    
  </div>
</div>
{% endblock %}

templates/customsettings/edit_schoolsubjects.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center">
    
  <div class="col-8 bg-light rounded p-5">
      <h2 class="text-center">Edit school Subjects</h2>
     
            {{ form|crispy }}
       
        <button type="submit" class="btn btn-primary">Save &raquo;</button>
    </form>
  </div>
</div>
{% endblock %}

templates/customsettings/registration.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="section mt-5 " style="height: 50vh;">
        <div class="col-8 offset-md  p-3   rounded shado" >
          <h1 >Registration</h1> 
            <form method="POST">
              {% csrf_token %}
              <!-- {{form|crispy}} -->
              <div >
              <div class="row m-3 ">
                <div class="col">
                    <label for="id_email" class="form-label requiredField">
                    Email<span class="asteriskField">*</span> </label>
                {{form.email}}
                </div>
              </div>
              <div class="row m-3 ">
                <div class="col">
                  <label for="id_email" class="form-label requiredField">
                    First Name<span class="asteriskField">*</span> </label>
                  {{form.first_name}}
                </div>
                
                <div class="col">
                  <label for="id_last_name" class="form-label requiredField">
                    Last Name<span class="asteriskField">*</span> </label>
                  {{form.last_name}}
                </div>
              </div>
            </div> 
            
            <div >
              <div class="row m-3">
                <div class="col">
                  <label for="id_user_type" class="form-label requiredField">
                    User Type<span class="asteriskField">*</span> </label>
                  {{form.user_type}} 
                    </div>
                    <div class="col">
                      <label for="id_user_type" class="form-label requiredField">
                        Position<span class="asteriskField">*</span> </label>
                      {{form.position}}
                    </div>
                  </div>
            </div>               
                  <div class=" p-3 ">
                <div class="row m-3">
                    <div class="col ">
                      <label for="id_user_type" class="form-label requiredField">
                        Password<span class="asteriskField">*</span> </label>
                      
                      {{form.password1}}
                    </div>
                  </div>
                <div class="row m-3 ">
                    <div class="col ">
                      <label for="id_user_type" class="form-label requiredField">
                        Password Confirm<span class="asteriskField">*</span> </label>
                      {{form.password2}}
                    </div>
                </div>
                </div><hr class="text-primary">
                <div class="d-grid">
                   <button type="submit" class=" btn btn-dark">Create User  </button>
                </div>
                 
            </form>
        </div>
      </div>


{% endblock %}

templates/customsettings/school_profile_form_step1.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="section w-75 bg1 p-3 offset-md-2 mt-5 shado">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>School Name</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ registered_school.school }}</td>
                    <td>{{ registered_school.address }}</td>
                    <td>{{ registered_school.phone_number }}</td>
                    <td>{{ registered_school.email }}</td>
                </tr>
            </tbody>
        </table>
              
        <h2>School Profile (create step1)</h2>
        <div class="progress mb-4">
            <div class="progress-bar" role="progressbar" style="width: 16.66%;" aria-valuenow="1" aria-valuemin="0" aria-valuemax="6">Step 1 of 6</div>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid">
                <button type="submit" class="btn bg3 text-white">School Profile (Next step 2)</button>
            </div>
            
        </form>
    </div>

{% endblock %}

templates/customsettings/schoolprofile_details.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="col-md-6 offset-md-3 bg1 shado p-5">
        <h1>School Profile Details</h1>
        <div>
            {% if schoolprofile.school_logo %}
                <img src="{{ schoolprofile.school_logo.url }}" width="250" alt="{{ schoolprofile.school }}" class="img-fluid mb-3">
            {% else %}
                <p>No logo available.</p>
            {% endif %}
        </div>
        
        <p><strong>School Name:</strong> {{ schoolprofile.school }}</p>
        <p><strong>Address:</strong> {{ schoolprofile.school.address }}</p>
        <p><strong>Email:</strong> {{ schoolprofile.school.email }}</p>
        <p><strong>Phone:</strong> {{ schoolprofile.school.phone_number }}</p>
        <p><strong>Facebook:</strong> <a href="{{ schoolprofile.facebook }}">{{ schoolprofile.facebook }}</a></p>
        <p><strong>Twitter:</strong> <a href="{{ schoolprofile.twitter }}">{{ schoolprofile.twitter }}</a></p>
        <p><strong>Instagram:</strong> <a href="{{ schoolprofile.instagram }}">{{ schoolprofile.instagram }}</a></p>
        <p><strong>Subjects:</strong>
            <ul>
                {% for subject in schoolprofile.school_subjects.all %}
                    <li>{{ subject }}</li>
                {% endfor %}
            </ul>
        </p>
       
          <a href="{% url 'update_schoolprofile' schoolprofile.id %}" class="btn bg3 text-white">Update School Profile</a>
          <a href="{% url 'create_schoolsubjects_step2' %}" class="btn bg3 text-white">Next Step 2</a>

        
    </div>
</div>
{% endblock %}

templates/customsettings/setup_step3.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <h2 class="text-warning">Setup Step 3: Social Pages</h2>
        <div class="progress mb-4">
            <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="3" aria-valuemin="0" aria-valuemax="6">Step 3 of 6</div>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Next</button>
        </form>
    </div>
{% endblock %}

templates/customsettings/setup_step6.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-warning">Setup Step 6: Subjects</h2>
    <div class="progress mb-4">
        <div class="progress-bar" role="progressbar" style="width: 86%;" aria-valuenow="6" aria-valuemin="0" aria-valuemax="">Step 6 of 7</div>
    </div>
    <div class="col-8  rounded  bg1 p-5">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
   
    
        
    
{% endblock %}

templates/customsettings/setup_step7.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-warning">Setup Step 7: Subjects</h2>
    <div class="progress mb-4">
        <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="7" aria-valuemin="0" aria-valuemax="7">Step 7 of 7</div>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Setup Completed </button>
    </form>
</div>
  

{% endblock%}

templates/customsettings/subject_list.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 bg1 p-5 shado">
                <h1>Subject List</h1>
                <ul>
                    {% for school_subject in all_subjects %}
                        <li>
                            <ul>
                                {% for subject in school_subject.subjects.all %}
                                    <li>{{ subject }}</li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'create_schoolsubjects_step2' %} " class="btn bg3 text-white">Edit Subject List</a>
                <a href="{% url 'class_name'%}" class="btn bg3 text-white">next step 4</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/customsettings/teacher_list.html
{% extends 'partials/base.html' %}
{% block title %}Teacher List{% endblock %}

{% block content %}
<div class="container offset-md-1 h-75 mt-5 scroll-container">
  <h2 class="mb-4">Teacher List</h2>

  <!-- Filter Form -->
  <form method="get" class="row g-3 mb-4">
    <div class="col-md-3">
      <label for="base_subject" class="form-label">Base Subject</label>
      <select name="base_subject" id="base_subject" class="form-select">
        <option value="">-- All Subjects --</option>
        {% for subject in base_subject %}
        <option value="{{ subject.id }}" {% if request.GET.base_subject == subject.id|stringformat:"s" %}selected{% endif %}>
          {{ subject }}
        </option>
        {% endfor %}
      </select>
    </div>

   

    <div class="col-md-3">
      <div class="form-check">
        <input type="checkbox" name="on_medical_leave" value="true" 
               class="form-check-input" id="medical_leave" 
               {% if request.GET.on_medical_leave == "true" %}checked{% endif %}>
        <label for="medical_leave" class="form-check-label">On Medical Leave</label>
      </div>
      <div class="form-check">
        <input type="checkbox" name="on_vocational_leave" value="true" 
               class="form-check-input" id="vocational_leave" 
               {% if request.GET.on_vocational_leave == "true" %}checked{% endif %}>
        <label for="vocational_leave" class="form-check-label">On Vocational Leave</label>
      </div>
    </div>

    <div class="col-md-3 d-flex align-items-end">
      <button type="submit" class="btn btn-primary me-2">Filter</button>
      <a href="{% url 'teacher_list' %}" class="btn btn-secondary">Reset</a>
    </div>
  </form>

  <!-- Teacher Table -->
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Base Subject</th>
          <th>Medical Leave</th>
          <th>Vocational Leave</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for teacher in all_teachers %}
        <tr>
          <td>{{ teacher.teacher.get_full_name }}</td>
          <td>{{ teacher.base_subject }}</td>
          <td>
            {% if teacher.on_medical_leave %}
            <span class="badge bg-danger">Yes</span>
            {% else %}
            <span class="badge bg-success">No</span>
            {% endif %}
          </td>
          <td>
            {% if teacher.on_vocational_leave %}
            <span class="badge bg-warning text-dark">Yes</span>
            {% else %}
            <span class="badge bg-success">No</span>
            {% endif %}
          </td>
          <td><a href="{% url 'view_teacher_profile' pk=teacher.pk %}">view</a></td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="4" class="text-center">No teachers found.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/customsettings/update_academic_calendar.html
{% extends "partials/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Update Academic Calendar</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/customsettings/update_schoolprofile.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-warning">Update SchoolProfile</h2>
    <div class="progress mb-4">
        <div class="progress-bar" role="progressbar" style="width: 16.66%;" aria-valuenow="1" aria-valuemin="0" aria-valuemax="6">Step 1 of 6</div>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Next</button>
    </form>
</div>
{% endblock %}